base:
    seed: &seed 0
model:
    # type: Qwen2
    # path: /data2/share/Qwen2.5/QwQ-32B-Preview
    # path: /data2/share/Qwen2.5/Qwen2.5-7B-Instruct
    # type: InternLM2
    # path: /data2/share/internlm/internlm2_5-7b-chat
    # type: Mistral
    # path: /data2/share/mistral/Mistral-7B-Instruct-v0.3
    type: Llama
    path: /data2/share/llama3.1/llama-3.1-8B-Instruct
    torch_dtype: auto
calib:
    name: pileval
    download: False
    n_samples: 128
    path: ./data/calib_data/pileval
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
eval:
    eval_pos: [fake_quant]
    name: wikitext2
    download: False
    path: ./data/eval_data/wikitext2
    bs: 1
    seq_len: 2048
    inference_per_block: False
    eval_token_consist: True
quant:
    method: GPTQ
    weight:
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 128
        need_pack: True
    special:
        actorder: True
        static_groups: True
        percdamp: 0.01
        blocksize: 128
        true_sequential: True
    quant_out: True
save:
    save_vllm: True
    # save_path: /data2/share/internlm/internlm2_5-7b-chat-GPTQ-w4a16
    # save_path: /data2/share/Qwen2.5/Qwen2.5-7B-Instruct-GPTQ-w4a16
    # save_path: /data2/share/Qwen2.5/QwQ-32B-Preview-GPTQ-w4a16
    # save_path: /data2/share/mistral/Mistral-7B-Instruct-v0.3-GPTQ-w4a16
    save_path: /data2/share/llama3.1/llama-3.1-8B-Instruct-GPTQ-w4a16
